# ============================================================
#  Configuración de la aplicación
# ============================================================
app.name    = RIWI Talent Manager
app.version = 1.0

# Vista a usar: "console" o "swing"
view.type   = swing
